### ISSUE TITLE
Cannot find the function "hosmerlem_test"

### ISSUE THREAD

**Issue by Tina-SONG** [jasongraf1/VADIS#2]
Hi, I am trying to get the H-L test result of my logistic model (glmer). While I have installed the package but I don't know what library I should load. May I know how to install and run this function in R? 

```
remotes::install_github("jasongraf1/VADIS")

```

**Comment by jasongraf1** [comment]
The package includes a custom function `hosmerlem_test()`, but that function is not exported. You can find the code for the function in the R folder of the repo. You can just copy the code from there!
